# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: nad.fun
networks:
- id: 10143
  start_block: 0
  contracts:
  - name: NadNameService
    address:
    - 0x3019BF1dfB84E5b46Ca9D0eEC37dE08a59A41308
    handler: src/EventHandlers.ts
    events:
    - event: AttributeSet(bytes32 indexed node, string key, string value)
    - event: Transfer(address indexed from , address indexed to , uint256 indexed id )
    
